// Config path -> panel component mapping
// Maps menu item IDs to their VyOS configuration paths

export const configSchema: Record<string, string[]> = {
  interfaces: ['interfaces'],
  firewall: ['firewall'],
  'firewall-ipv4': ['firewall', 'ipv4'],
  'firewall-ipv6': ['firewall', 'ipv6'],
  'firewall-bridge': ['firewall', 'bridge'],
  'firewall-groups': ['firewall', 'group'],
  'firewall-zones': ['firewall', 'zone'],
  'firewall-flowtables': ['firewall', 'flowtable'],
  'firewall-global': ['firewall', 'global-options'],
  nat: ['nat'],
  'nat-source': ['nat', 'source'],
  'nat-destination': ['nat', 'destination'],
  'nat-nat64': ['nat', 'nptv6'],
  'nat-nat66': ['nat', 'nat66'],
  'nat-cgnat': ['nat', 'cgnat'],
  routing: ['protocols'],
  'routing-static': ['protocols', 'static'],
  'routing-bgp': ['protocols', 'bgp'],
  'routing-ospf': ['protocols', 'ospf'],
  'routing-ospfv3': ['protocols', 'ospfv3'],
  'routing-isis': ['protocols', 'isis'],
  'routing-rip': ['protocols', 'rip'],
  'routing-babel': ['protocols', 'babel'],
  'routing-bfd': ['protocols', 'bfd'],
  'routing-mpls': ['protocols', 'mpls'],
  'routing-sr': ['protocols', 'segment-routing'],
  'routing-igmp': ['protocols', 'igmp-proxy'],
  'routing-pim': ['protocols', 'pim'],
  'routing-multicast': ['protocols', 'multicast'],
  'routing-rpki': ['protocols', 'rpki'],
  'routing-failover': ['protocols', 'failover'],
  policy: ['policy'],
  'policy-routemaps': ['policy', 'route-map'],
  'policy-accesslists': ['policy', 'access-list'],
  'policy-prefixlists': ['policy', 'prefix-list'],
  'policy-aspath': ['policy', 'as-path-list'],
  'policy-community': ['policy', 'community-list'],
  'policy-extcommunity': ['policy', 'extcommunity-list'],
  'policy-largecommunity': ['policy', 'large-community-list'],
  'policy-localroute': ['policy', 'local-route'],
  vpn: ['vpn'],
  'vpn-ipsec-s2s': ['vpn', 'ipsec'],
  'vpn-ipsec-ra': ['vpn', 'ipsec', 'remote-access'],
  'vpn-dmvpn': ['vpn', 'nhrp'],
  'vpn-l2tp': ['vpn', 'l2tp'],
  'vpn-openconnect': ['vpn', 'openconnect'],
  'vpn-pptp': ['vpn', 'pptp'],
  'vpn-sstp': ['vpn', 'sstp'],
  services: ['service'],
  'services-dhcp': ['service', 'dhcp-server'],
  'services-dhcpv6': ['service', 'dhcpv6-server'],
  'services-dhcprelay': ['service', 'dhcp-relay'],
  'services-dns': ['service', 'dns'],
  'services-ssh': ['service', 'ssh'],
  'services-https': ['service', 'https'],
  'services-ntp': ['service', 'ntp'],
  'services-snmp': ['service', 'snmp'],
  'services-lldp': ['service', 'lldp'],
  'services-pppoe': ['service', 'pppoe-server'],
  'trafficpolicy': ['traffic-policy'],
  ha: ['high-availability'],
  'ha-vrrp': ['high-availability', 'vrrp'],
  'ha-virtual-server': ['high-availability', 'virtual-server'],
  loadbalancing: ['load-balancing'],
  'lb-wan': ['load-balancing', 'wan'],
  'lb-haproxy': ['load-balancing', 'haproxy'],
  containers: ['container'],
  'containers-list': ['container', 'name'],
  'containers-networks': ['container', 'network'],
  'containers-registries': ['container', 'registry'],
  pki: ['pki'],
  'pki-ca': ['pki', 'ca'],
  'pki-certs': ['pki', 'certificate'],
  'pki-keypairs': ['pki', 'key-pair'],
  'pki-dh': ['pki', 'dh'],
  vrf: ['vrf'],
  system: ['system'],
  'system-hostname': ['system', 'host-name'],
  'system-dns': ['system', 'name-server'],
  'system-timezone': ['system', 'time-zone'],
  'system-users': ['system', 'login'],
  'system-syslog': ['system', 'syslog'],
  'system-conntrack': ['system', 'conntrack'],
  'system-ip': ['system', 'ip'],
  'system-console': ['system', 'console'],
  'system-scheduler': ['system', 'task-scheduler'],
  'system-watchdog': ['system', 'watchdog'],
  'system-options': ['system', 'option'],
  'system-acceleration': ['system', 'acceleration'],
  operations: [],
  'ops-sysinfo': [],
  'ops-reboot': [],
  'ops-show': [],
};
